romana/romana

- README.md
Tiny little change. As I was quickly going through the instructions in the README before, it happened to me twice that I simply skipped the part about the SSH key. While those little sub-headings in the 'Tools' section don't look great, I'm hoping that they at least force people to note that there's something written about the key.
> Small changes in README.

- README.md
- aws_devstack.md
- aws_kubernetes.md
- devstack_romana.md
- kubernetes_romana.md
- vagrant_devstack.md
- vagrant_kubernetes.md
Since this is a replacement / overwrite of the existing docs, it might make sense to review just the files, instead of the diff between the earlier README.
This is something that should be dropped in at the same time as the updated installer.
I've put it on a separate branch to try and keep the changes clear.
Once reviewed and OKed, it'll get merged to `kubernetes` then `kubernetes` merged to `master`.
> README changes across aws/vagrant/devstack/kubernetes

- romana-install/group_vars/kube_nodes
- romana-install/roles/romana/kubernetes-postinstall/files/demo/romana-np-frontend-to-backend.json
- romana-install/roles/stack/kubernetes/install-minion/tasks/main.yml
kubernetes [1.2.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.2.0) dropped today, requiring a retest and minor changes to make our basic setup and demo continue to work with 1.2.
This PR is to merge those onto the kube-namespaces branch for now, until we're ready to merge that one to master. (Could I get confirmation on the kube-namespaces PR also? It'd be good to close both.)
> installer updated for kubernetes 1.2.0

- romana-install/create_hosts.static.yml
- romana-install/delete_hosts.static.yml
- romana-install/pre-delete.yml
- romana-install/roles/summary/templates/devstack_stackinfo
- romana-install/roles/summary/templates/kubernetes_stackinfo
- romana-install/roles/system/tasks/main.yml
- romana-install/romana-setup
- static_hosts.md
Provides a way for users to install Romana using this setup tool, but on hosts they have provisioned themselves.
The user is expected to provide an Ansible inventory and ensure the host has been configured appropriately to the same level as our automatically provisioned hosts.
(Eg: SSH available, key-based authentication, sudo access without a password prompt.)
> Static hosts

- romana-install/localhost
This should be merged so the virtualenv users don't get tripped up by weird errors about missing modules.
> Specifying interpreter allows installer to work in virtualenv

- romana_setup.md
Using a separate PR for this, because #99 was branched before the `romana_setup.md` file was added.
> Doc updates. Relates to 'more installer changes' PR.

- romana-install/create_hosts.static.yml
- romana-install/roles/system/tasks/main.yml
- romana-install/roles/system/tasks/ssh_keys.yml
Opening this PR to discuss whether it's appropriate to do this for static hosts.
It's convenient if the user hasn't already configured a common SSH keypair on all hosts, and convenient for SSH-ing into openstack compute instances from the host, because this key gets added as a nova keypair.
But.. if a common keypair _was_ already installed (for this `ansible_ssh_user`) then it'll overwrite it.
Is that bad?
The workaround would be copying the desired keypair to `romana_id_rsa` and `romana_id_rsa.pub` before installing, or creating a different user on the hosts.
> Generate and use SSH key internally even for static hosts.

- romana-install/group_vars/all/go
- romana-install/group_vars/all/romana
- romana-install/roles/romana/install-agent/tasks/main.yml
- romana-install/roles/romana/install-agent/tasks/romana_from_github.yml
- romana-install/roles/romana/install-agent/tasks/romana_from_s3.yml
- romana-install/roles/romana/install-master/files/build_romana_core
- romana-install/roles/romana/install-master/tasks/main.yml
- romana-install/roles/romana/install-master/tasks/romana_from_github.yml
- romana-install/roles/romana/install-master/tasks/romana_from_s3.yml
- romana-install/roles/romana/install-master/tasks/romana_prep.yml
- romana-install/roles/system/tasks/packages_debian.yml
- romana-install/roles/system/tasks/packages_redhat.yml
- romana-install/roles/system/tasks/ssh_keys.yml
- romana-install/roles/system/templates/known_hosts
Allows spinning up a cluster that builds the Core apps from github instead of downloading from S3.
Need to append `-e romana_core_source=github` at the end of the romana-setup install command.
Eg: `./romana-setup -n bfs -s kubernetes install -e romana_core_source=github`
(It may later become a direct option of `romana-setup`.)
One bonus feature: since we needed copying files via rsync (ssh) without a password prompt, the setup now generates a `known_hosts` file and puts that on each cluster host. No more `Are you sure you want to continue connecting (yes/no)?` prompts.
> Build core from source

- devstack_romana.md
- kubernetes_romana.md
With the new `romana` tool being used by default, the documentation needed to be updated to match its usage and output. This PR covers that for kubernetes and devstack.
> Update examples using `romana`.

- romana-install/romana-setup
- romana_setup.md
This makes it easier to create clusters with a larger number of compute nodes.
It's already possible by specifying the correct, exact `-e` option in the parameters passed to Ansible. This is just to make it easier, with a `-c number` option.
Arbitrarily limited to 199, only tested to 10.
> Allow number of compute nodes as romana-setup option.

- romana-install/group_vars/devstack_nodes
Updated cache pushed to S3.
This bumps the revision/filename the installer is configured to use.
> Refresh pip cache, reducing delay in install time for devstack

- romana-install/tests.kubernetes.yml
- romana-install/tests.yml
- test/kubernetes-cluster/tests
Update the tests to check for the correct services on 0.9.x (new or renamed.
Small fix in how test logs are handled, affecting all cluster types.
> Fix test steps to avoid errors. Update service names used in 0.9

- romana-install/group_vars/all/romana
After merging changes across, tagging them and verifying with running clusters, it seems we can bump the version that the installer deploys to v0.9.1.
Kubernetes cluster has been tested with the updated demo.sh and with the work-in-progress end to end tests.
Devstack cluster has been tested also with the end-to-end tests. There's the known limitation that we can't SSH into the VMs from the host. Docs have been revised in PR #117 to address that. (Already merged since it affected 0.9.0 also.
> Version bump to v0.9.1

- romana-install/group_vars/all/romana
- romana-install/group_vars/all/stack
- romana-install/roles/romana/install-agent/tasks/policy_agent.yml
- romana-install/roles/romana/install-agent/tasks/romana_from_github.yml
- romana-install/roles/romana/install-agent/tasks/romana_from_s3.yml
- romana-install/roles/romana/install-master/tasks/romana_from_github.yml
- romana-install/roles/stack/devstack/install-controller/tasks/main.yml
- romana-install/roles/stack/devstack/install-controller/templates/local.conf
- romana-install/roles/stack/kubernetes/prep/tasks/romana_kube.yml
- romana-install/roles/system/tasks/ssh_keys.yml
- romana-install/romana-setup
Additional installer options for creating clusters using custom repos and branches.
The options are very dev-team oriented, so they are not currently part of the usage documentation.
New options:
--source: Build romana from source.
--github-repo: Full path to the github location for repos. `https://github.com/username` or `git@github.com:username` format
--github-user: A shorter way of describing the `git@github.com:username` path.
--github-key: The path to the SSH key required to access the repository
--core-branch: Name of branch/tag/commit to pull for `core`
--networking-branch: Name of branch/tag/commit to pull for `networking-romana`
--kube-branch: Name of branch/tag/commit to pull for `kube`
Example usage:
`./romana-setup -n kube123 -s kubernetes --source --github-user aprivateorg …
> Allow custom repos when installing Romana from source

- romana-install/roles/system/tasks/packages_debian.yml
This was affecting static install in Chris's cluster.
> Use rsync instead of synchronize here.

- romana-install/post-tests.yml
- romana-install/tests.devstack.yml
- test/openstack-cluster/connectivity-test
- test/openstack-cluster/run-vms-each-host
- test/openstack-cluster/tests
An end-to-end test for devstack.
Basic behaivor is
- spin up two VMs
- find out which host the first one is on
- ping that host
- ssh to first VM via that host
- ssh to first VM and ping second VM
- insert SSH key into first vm
- ssh to first VM then across to second VM
Fun note: cirros / dropbear uses its own unique SSH key format, so it needs to be copied on then converted.
> Adds end-to-end test for devstack

- romana-install/roles/stack/kubernetes/install-minion/tasks/packages_debian.yml
- romana-install/roles/stack/kubernetes/install-minion/tasks/packages_redhat.yml
- romana-install/roles/stack/openstack/prep/tasks/packages_redhat.yml
- romana-install/roles/stack/openstack/prep/tasks/packages_ubuntu.yml
- romana-install/roles/system/tasks/packages_debian.yml
- romana-install/roles/system/tasks/packages_redhat.yml
Because it's useful -- for functionality, for operations, for tests that interact with json, etc.
Seems sensible to do it here than selectively in multiple places.
> Install jq at system-prep stage on all nodes.

- romana-install/group_vars/all/romana
- test/kubernetes-cluster/frontend-to-backend.yml
- test/kubernetes-cluster/tenant-frontend-backend
This PR changes the version installed by the installer to v0.9.3.2.
Tests for this release were done on rc.2 with the results below:
Kubernetes: all tests passed
```
016-10-07 04:50:28 (ip-192-168-99-10:clustertests) Test #1: Check that Kubernetes services are running on master : PASSED
2016-10-07 04:50:29 (ip-192-168-99-10:clustertests) Test #2: Check that Romana services are running on master : PASSED
2016-10-07 04:50:30 (ip-192-168-99-10:clustertests) Test #3: Check that Kubernetes services are running on minion : PASSED
2016-10-07 04:50:31 (ip-192-168-99-10:clustertests) Test #4: Check that Romana services are running on minion : PASSED
2016-10-07 04:50:32 (ip-192-168-99-10:clustertests) Test #6: Pull docker containers used in later tests : PASSED
2016-10-07 04:50:55 …
```
> Release v0.9.3.2

- containerize/specs/romana-agent-daemonset.yml
- containerize/specs/romana-services-manifest.yml
- containerize/targets/agent/run-romana-agent
- romana-install/group_vars/all/romana
This PR releases 0.9.3.4 -- some bug fixes and minor improvements for containerized setups.
Tests are passing on AWS for all stacks.
Kubernetes tests:
```
2016-10-30 23:17:10 (ip-192-168-99-10:clustertests) Test #1: Check that Kubernetes services are running on master : PASSED
2016-10-30 23:17:11 (ip-192-168-99-10:clustertests) Test #2: Check that Romana services are running on master : PASSED
2016-10-30 23:17:13 (ip-192-168-99-10:clustertests) Test #3: Check that Kubernetes services are running on minion : PASSED
2016-10-30 23:17:13 (ip-192-168-99-10:clustertests) Test #4: Check that Romana services are running on minion : PASSED
2016-10-30 23:17:14 (ip-192-168-99-10:clustertests) Test #6: Pull docker containers used in later tests : PASSED
2016-10-30 23:17:35 …
```
> Release v0.9.3.4

- romana-install/roles/provision/create-vagrant-hosts/templates/Vagrantfile
- vagrant_kubernetes.md
Fix a couple of issues experienced when playing with the Kubernetes on Vagrant version.
Initially the nginx containers of the demo stayed in ContainerCreating state - as romana-ipam was erroring with duplicate entries in the DB, both saying <user>-compute01, this was fixed via the Vagrantfile template correction.
Secondly the kubernetes binary tarball cache is causing the get_url to not be changed & so the extract not run when making a second cluster - the workaround isn't pretty but functional.  Note that the etcd download cache would suffer from the same fate but is broken due to mismatching filenames - left alone for minimum changes (I'm not testing widely).
Also a docs copy-pasta fix.
> Fix vagrant hostnames

- containerize/specs/romana-agent-daemonset.yml
- containerize/specs/romana-kops.yml
- containerize/specs/romana-kubeadm.yml
- containerize/specs/romana-services-daemonset.yml
- containerize/specs/romana-services-manifest.yml
- romana-install/group_vars/all/romana
This PR releases v0.9.3.5, containing some small bug fixes and improvements.
It is passing automated tests.
Kubernetes:
```
2016-11-09 23:18:20 (ip-192-168-99-10:clustertests) Test #1: Check that Kubernetes services are running on master : PASSED
2016-11-09 23:18:20 (ip-192-168-99-10:clustertests) Test #2: Check that Romana services are running on master : PASSED
2016-11-09 23:18:22 (ip-192-168-99-10:clustertests) Test #3: Check that Kubernetes services are running on minion : PASSED
2016-11-09 23:18:23 (ip-192-168-99-10:clustertests) Test #4: Check that Romana services are running on minion : PASSED
2016-11-09 23:18:23 (ip-192-168-99-10:clustertests) Test #6: Pull docker containers used in later tests : PASSED
2016-11-09 23:18:41 (ip-192-168-99-10:clustertests) Test #8: Check namespace …
```
> Release v0.9.3.5

- containerize/specs/romana-agent-daemonset.yml
- containerize/specs/romana-kops.yml
- containerize/specs/romana-kubeadm.yml
- containerize/specs/romana-services-daemonset.yml
- containerize/specs/romana-services-manifest.yml
- romana-install/group_vars/all/romana
- romana-install/roles/stack/kubeadm/postinstall/files/romana-kubeadm.yml
This releases version 1.0.1 of Romana.
This is to deliver installation scripts and containers that support kubernetes v1.6.x and installs using kubeadm v1.6.1+.
> Release v1.0.1

- containerize/specs/romana-kops.yml
- containerize/specs/romana-kubeadm.yml
- romana-install/roles/stack/kubeadm/postinstall/files/romana-kubeadm.yml
- romana-install/roles/stack/kubeadm/postinstall/templates/romana-localbuild.yml
This adds a section to the romana-kubeadm yaml file to specify seLinuxOptions.
On systems with SELinux configured and set to enforcing, some containers were unable to launch because of using paths in `/var`. Those paths weren't permitted by standard selinux policies for docker/kubernetes.
This fixes #169.
> Add seLinuxOptions

- containerize/targets/daemon/kops-network-us-east-1.json
The predefined config for us-east-1 has 8 hostgroups for each of the 6 regions.
Each of these groups becomes a route in the VPC routing table - 48 routes.
48 routes is too close to the "50 route limit", as some routes are needed for local instances, internet gateway and any user-defined routes such as VPC peering connections.
This PR reduces the predefined config for us-east-1 to have 4 hostgroups per region, so only 24 routes will be created by vpcrotuer.
> Reduce the number of predefined groups for us-east-1

- containerize/specs/romana-kops.yml
- docs/kubernetes/romana-kops.yml
The vpcrouter tool uses the AWS API endpoints to make changes to the routing tables within a VPC.
To look up the API endpoint, it needs DNS.
However, kube-dns runs as a service, and some of the the pods providing that service might be running in a different region _before_ vpcrouter has created the routes to access pods there.
It isn't immediately noticeable in some installs, because the first instance of kube-dns runs on a directly-reachable master node.
It becomes a problem when kube-dns is scaled up to more pods - some reachable, some not.
This PR changes the vpcrouter pod to use `hostNetwork: true` to ensure it is always able to look up the AWS API endpoint addresses and bring the pod network into a fully routed state.
> Use hostNetwork for vpcrouter
